import "./globals.css";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/geist/Geist-Variable.woff2",   // ✅ relative to layout.js
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap",
});

const geistMono = localFont({
  src: "./fonts/geist/GeistMono-Variable.woff2", // ✅ relative to layout.js
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap",
});

export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
